[package]
name = "news"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.128", features = [ "derive" ] }
serde_json = "1.0.66"
ureq = "2.1.1"
colour = "0.6.0"

